# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hshimizu <hshimizu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/24 17:27:29 by hshimizu          #+#    #+#              #
#    Updated: 2024/04/26 16:05:15 by hshimizu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		:= Animal

CXXFLAGS	:= -Wall -Wextra -Werror
CXXFLAGS	+= -std=c++98

SRCS		:= main.cpp
SRCS		+= Animal.cpp
SRCS		+= Brain.cpp
SRCS		+= Cat.cpp
SRCS		+= Dog.cpp
SRCS		+= WrongAnimal.cpp
SRCS		+= WrongCat.cpp
SRCS		+= WrongDog.cpp

$(NAME): $(SRCS)
	$(CXX) $(CXXFLAGS) $^ -o $@

.PHONY: clean
clean: $(NAME)
	$(RM) $^
